import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Chat to CSV</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Attendance Collector!
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className={styles.grid}>
          <Link href={"/core"}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Chat text to CSV &rarr;</h2>
            <p>Copy paste everything from Chat to generate attendance CSV/Sheet.</p>
          </a></Link>

          
        </div>
      </main>

      <footer className={styles.footer}>
          Scripted by -- {' '} <strong>{' '}CSE-221-F Programmers</strong>
      </footer>
    </div>
  )
}

export default Home
